<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AudioQualityEnhancer.Tests\**\*" />
    <Compile Remove="Temp\**\*" />
    <EmbeddedResource Remove="AudioQualityEnhancer.Tests\**\*" />
    <EmbeddedResource Remove="Temp\**\*" />
    <None Remove="AudioQualityEnhancer.Tests\**\*" />
    <None Remove="Temp\**\*" />
    <Page Remove="AudioQualityEnhancer.Tests\**\*" />
    <Page Remove="Temp\**\*" />
  </ItemGroup>

</Project>
